receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: "http://data-prepper:2021/trace/ingest"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
